### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by btea** [btea/test#1]
https://user-images.githubusercontent.com/24516654/190611743-47c485ba-1054-4619-a341-4155a6cfc772.mp4

**Comment by BlackHole1** [comment]
Hi @btea 👋. This is an empty video.

**Comment by btea** [comment]
Oh, sorry, I will try to reupload one.

**Comment by btea** [comment]
@BlackHole1 There seems to be a problem with the video, so I replaced it with a picture

![image](https://user-images.githubusercontent.com/24516654/190613497-f239e109-4a35-442a-ad46-e4f61f1e6ee8.png)

**Comment by btea** [comment]
Can you go to the `run.md` file and modify the line I selected in the picture?

**Comment by BlackHole1** [comment]
This is expected. See: https://support.crowdin.com/enterprise/common-questions-managers/#how-to-hide-a-string-from-displaying-in-the-editor

https://user-images.githubusercontent.com/8198408/190623874-424642e0-f81b-42d9-b56e-5ac5ccb94095.mp4

**Comment by btea** [comment]
ok, thank you for the explanation. ❤
